# -*- coding: utf-8 -*-
"""오브젝트 디텍션.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HW6rbeESA_BwU0ISNnH7O1Liw8atjG-a
"""

!nvidia-smi -L

from google.colab import drive

drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
#  %tensorflow_version 1.x

!git clone https://github.com/heartkilla/yolo-v3.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolo-v3
!pip install -r /content/yolo-v3/requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolo-v3
!wget -P /content/yolo-v3/weights https://pjreddie.com/media/files/yolov3.weights

import tensorflow as tf

tf.__version__

!python /content/yolo-v3/load_weights.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolo-v3
!python detect.py images 0.5 0.5 data/images/dog.jpg data/images/office.jpg